// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHOLhsW0uO4cHK_nhJl1gk6eBgMM9v3e0',
    appId: '1:5902308333:web:7a280c8640ccf72c0b0de4',
    messagingSenderId: '5902308333',
    projectId: 'myginie-pr',
    authDomain: 'myginie-pr.firebaseapp.com',
    storageBucket: 'myginie-pr.appspot.com',
    measurementId: 'G-GDL7Z0QBCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXiDXBa0Phqf95fQWMVIUK5AGTUA3WDME',
    appId: '1:5902308333:android:6655dccf01a0abe80b0de4',
    messagingSenderId: '5902308333',
    projectId: 'myginie-pr',
    storageBucket: 'myginie-pr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb59tM-gGf0GLkuicUf0atq87liCiuaGU',
    appId: '1:5902308333:ios:17159d780965c9d30b0de4',
    messagingSenderId: '5902308333',
    projectId: 'myginie-pr',
    storageBucket: 'myginie-pr.appspot.com',
    iosClientId: '5902308333-3b84rr2objvj8hd2ng2ttorbicc2m7t0.apps.googleusercontent.com',
    iosBundleId: 'com.ginieman.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb59tM-gGf0GLkuicUf0atq87liCiuaGU',
    appId: '1:5902308333:ios:17159d780965c9d30b0de4',
    messagingSenderId: '5902308333',
    projectId: 'myginie-pr',
    storageBucket: 'myginie-pr.appspot.com',
    iosClientId: '5902308333-3b84rr2objvj8hd2ng2ttorbicc2m7t0.apps.googleusercontent.com',
    iosBundleId: 'com.ginieman.myproject',
  );
}
